### PR TITLE
Cisco switch power

### PR DESCRIPTION
**Pull request by jhughesbiot**
Update power resolving method to account for bug found here

https://github.com/faucetsdn/daq/issues/233#issuecomment-616644165

### CODE REVIEW

**Comment by jhughesbiot** [comment]
@grafnu @pisuke 
I have been unable to test these changes since it appears the current code breaks my ethernet adapter that is connected to the switch.  If I run a bin/net_clean and reset the adapter, it has the correct IP defined in the system.conf file but during run, it can't actually ping the switch.  Once the test is completed, I can see the IP address has been lost.  Not sure what's happened to the network stack but I can't test this anymore on my hardware.

**Comment by grafnu** [comment]
If you can include the inst/cmdrun.log file from the run that would help
with diagnostics.

**Comment by jhughesbiot** [comment]
Here you go.  
[cmdrun.log](https://github.com/faucetsdn/daq/files/4511376/cmdrun.log)
To help illustrate the issue, this is what my adapter looks like before the test when it has a valid IP.

```
ens9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.9  netmask 255.255.255.0  broadcast 192.168.100.255
```

The cmdrun.log file does confirm in the beginning communication is up

```
Bridging ens9 to ctrl-br
Checking external connection to 192.168.100.99
PING 192.168.100.99 (192.168.100.99) 56(84) bytes of data.
64 bytes from 192.168.100.99: icmp_seq=1 ttl=255 time=1.75 ms
64 bytes from 192.168.100.99: icmp_seq=2 ttl=255 time=0.708 ms
```

The switch activate.log shows that it can no longer communicate by the time this module is run and the IP is now changed:


Configuring network with local address 192.168.100.12/24.
Switch Test with model CISCO_9300.
Switch test with port 1.
PING 192.168.100.99 (192.168.100.99) 56(84) bytes of data.
From 192.168.100.12 icmp_seq=1 Destination Host Unreachable
From 192.168.100.12 icmp_seq=2 Destination Host Unreachable
From 192.168.100.12 icmp_seq=3 Destination Host Unreachable
From 192.168.100.12 icmp_seq=4 Destination Host Unreachable
From 192.168.100.12 icmp_seq=5 Destination Host Unreachable
From 192.168.100.12 icmp_seq=6 Destination Host Unreachable
From 192.168.100.12 icmp_seq=7 Destination Host Unreachable
From 192.168.100.12 icmp_seq=8 Destination Host Unreachable
From 192.168.100.12 icmp_seq=9 Destination Host Unreachable

--- 192.168.100.99 ping statistics ---
10 packets transmitted, 0 received, +9 errors, 100% packet loss, time 9206ms
pipe 4


And then once the test ends, the adapter can be confirmed it has lost its ip configuration.
```
ens9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 52:54:00:da:c6:92  txqueuelen 1000  (Ethernet)
```

**Comment by jhughesbiot** [comment]
Just to confirm some things on my end, I pulled the release 1.1.0 and ran a successful DAQ cmd/run connected to a cisco switch to confirm the issue isn't present there and it worked as expected.  The adapter at the end of the test had also lost it's configured IP from the OS so this may be an expected behavior, at least in contexts of a test being run, and nothing to be concerned with for further reporting on this issue.

> Actually -- that brings up something -- why is the setting configured as
192.168.100.9 sometimes and 192.168.100.12 others?  The IP address if the
switch is 192.168.100.99, right?

I don't know why the system is deciding to use .12 instead of .9.  It's configured in the system.conf to be ext_ofip=192.168.100.9/24 and at the OS level for that IP which seems to be the case at the start of DAQ but not by the time the switch module is run.

Output of physical_sec:

```
Activating venv
Loading config from local/system.conf into inst/config/system.conf
Cleaning switch bridge, if any...
Configuring control interface ens9 at 192.168.100.9/24
Checking external connection to 192.168.100.99
PING 192.168.100.99 (192.168.100.99) 56(84) bytes of data.
64 bytes from 192.168.100.99: icmp_seq=1 ttl=255 time=0.915 ms
64 bytes from 192.168.100.99: icmp_seq=2 ttl=255 time=0.800 ms

--- 192.168.100.99 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.800/0.857/0.915/0.064 ms

DAQ autoclean ip link set down dev ens9
Done with physical switch configuration.

```

While running a persistent ping throughout the entire cmd/run, the ping never failed but the switch module still fails to ping so it appears there's something in the network configuration that is setting up that container is failing.

**Comment by pisuke** [comment]
@jhughesbiot thanks for updating the code.

I've cloned this branch, rebuilt and tested against a PoE physical device.

See attached reports for the x230 and 9300 switches.

[device_report_at_x230.pdf](https://github.com/faucetsdn/daq/files/4525744/device_report_at_x230.pdf)

[device_report_cisco_9300.pdf](https://github.com/faucetsdn/daq/files/4525745/device_report_cisco_9300.pdf)

They still have the problem of not putting any information for the pass case in the summary table.

The AT x230 switch includes diagnostic information in the body of the report, while the Cisco 9300 doesn't. Can this please be included? 

The activate.log file includes enough information, can this please be included?

```
 Inline Power Mode: auto
 Operational status: on
 Device Detected: yes
 Device Type: Ieee PD
 IEEE Class: 4
 Discovery mechanism used/configured: Ieee and Cisco
 Police: off
 Power Allocated 
 Admin Value: 30.0
 Power drawn from the source: 30.0
 Power available to the device: 30.0
 
 Actual consumption
 Measured at the port: 3.1
 Maximum Power drawn by the device since powered on: 3.4
 
 Absent Counter: 0
 Over Current Counter: 0
 Short Current Counter: 0
 Invalid Signature Counter: 0
 Power Denied Counter: 0
 Power Negotiation Used: None
 LLDP Power Negotiation --Sent to PD--      --Rcvd from PD--
   Power Type:          -                    -
   Power Source:        -                    -
   Power Priority:      -                    -
   Requested Power(W):  -                    -
   Allocated Power(W):  -                    -
Four-Pair PoE Supported: No
Spare Pair Power Enabled: No
Four-Pair PD Architecture: N/A
arup-daq-lab#

Processing Command Response:
Interface: Gi1/0/6
 Inline Power Mode: auto
 Operational status: on
 Device Detected: yes
 Device Type: Ieee PD
 IEEE Class: 4
 Discovery mechanism used/configured: Ieee and Cisco
 Police: off
 Power Allocated 
 Admin Value: 30.0
 Power drawn from the source: 30.0
 Power available to the device: 30.0
 
 Actual consumption
 Measured at the port: 3.1
 Maximum Power drawn by the device since powered on: 3.4
 
 Absent Counter: 0
 Over Current Counter: 0
 Short Current Counter: 0
 Invalid Signature Counter: 0
 Power Denied Counter: 0
 Power Negotiation Used: None
 LLDP Power Negotiation --Sent to PD--      --Rcvd from PD--
   Power Type:          -                    -
   Power Source:        -                    -
   Power Priority:      -                    -
   Requested Power(W):  -                    -
   Allocated Power(W):  -                    -
Four-Pair PoE Supported: No
Spare Pair Power Enabled: No
Four-Pair PD Architecture: N/A
rxQueue.isEmpty:5
expectedLength:1000
23:15:11.502receiveDataLen:14receiveData:
arup-daq-lab#
login_report:
RESULT pass connection.port_link
RESULT pass connection.port_speed
RESULT pass connection.port_duplex
RESULT pass poe.power
RESULT pass poe.negotiation
RESULT pass poe.support


RESULT pass connection.port_link
RESULT pass connection.port_speed
RESULT pass connection.port_duplex
RESULT pass poe.power
RESULT pass poe.negotiation
RESULT pass poe.support
--------------------
```

Thanks!

**Comment by jhughesbiot** [comment]
@grafnu @pisuke 
It appears that the issue to resolve the DHCP is no longer working today.  I tried to run the cmd/run before looking into this further and I am continually stuck at this point until timeout.

```
INFO:host:Target port 1 waiting for ip as 00:1e:c6:00:21:ea
INFO:host:Target port 1 using normal DHCP mode, wait 0
INFO:runner:Port 1 dpid 737894404660 learned 00:1e:c6:00:21:ea
```
I have tried rebuilding many times and no luck so I'm again stuck on making progress on this until the network becomes more stable.

**Comment by jhughesbiot** [comment]
I have managed to get this test working on my physical switch and confirmed the PoE updates function with both a PoE device and a non-PoE device.  

@pisuke 
Test messaging was added to the pass results as well.  The skip and fail tests already contained these messages.

**Comment by jhughesbiot** [comment]
@pisuke 
Readme added for the switch_test.  Let me know if you run into any other issues with testing so we can close these out.  

@grafnu 
Right now the only failure on the build seems to be the flaky bacnet test but this last one was a success so it should be ready to merge unless there's more feedback on this update.

**Pull request merged**
