### PR TITLE
Timeouts and retry support for authenticator

### PR DESCRIPTION
**Pull request by anurag6**

### CODE REVIEW

**Comment by henry54809** [comment]
Maybe instead of pulling in forch’s heartbeat scheduler, you can give the “interval observable” a try. Pretty low impact.

**Comment by anurag6** [comment]
> Maybe instead of pulling in forch’s heartbeat scheduler, you can give the “interval observable” a try. Pretty low impact.

Let me take a look at it. I still need to add retry support. Will check it out once that's done.

**Comment by grafnu** [comment]
It's not an inherently bad idea, but I'm guessing there's still a fair
amount to be done to get 802.1x across the finish line so I'd just be wary
of distractions...

**Review by grafnu — APPROVED** [review]

**Comment by anurag6** [comment]
Fair enough. Probably something to look at the next time.

**Pull request merged**
